version: "3.9"

services:

  web:
    container_name: bitcoinlottery
    restart: always
    build: .
    ports:
      - "80:80"
    volumes:
      - .:/app
      - node_modules:/app/node_modules
    environment:
      MONGO_USERNAME: root
      MONGO_PASSWORD: password
    depends_on:
      - mongo

  mongo:
    image: mongo:4.4.2
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    ports:
      - "27017:27017"

volumes:
  dbdata:
  node_modules: